services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vue-spa-front:latest
    container_name: vue-spa-front
    ports:
      - "8080:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge